# configs.yaml
random_seed: 42

model:
  sample_rate: 16000
  n_mels: 80
  mel_hop_length: 320
  hidden_dim: 512
  lstm_layers: 2
  encoder_strides: [2, 4, 5, 8]
  speaker:
    dim: 512
    ref_enc_filters: [32, 32, 64, 64, 128, 128]
    ref_enc_size: 3
    ref_enc_strides: [1, 2, 2, 2, 2, 2]
    ref_enc_pad: 1
    ref_enc_gru_size: 256
    num_heads: 4
  bottleneck:
    num_quantizers: 8
    codebook_size: 1024
    codebook_dim: 128
    decay: 0.99
    commitment_weight: 0.1
    use_cosine_sim: true
    kmeans_init: false
    threshold_ema_dead_code: 2.0

training:
  # batch_size: 6 # 24GB VRAM with 32 percision
  batch_size: 24 # 48GB VRAM with bf16-mixed precision
  # accumulate_grad_batches: 4 # Automatic gradient accumulation is not supported for manual optimization
  max_steps: 500000
  max_epochs: 10
  lr: 1.5e-4  # 2.0e-4 / 32 * 24
  gamma: 0.9
  betas: [0.8, 0.999]
  weight_decay: 1.0e-5
  num_workers: 8
  precision: "bf16"
  # precision: "32"
  target_samples: 96000 # 6s * 16000Hz
  val_check_interval: 0.1
  early_stop_patience: 10
  early_stop_monitor: "val/rec"
  early_stop_mode: "min"
  log_every_n_steps: 1
  # log_every_n_steps: 100

losses:
  lambda_r: 45.0
  lambda_a: 1.0
  lambda_c: 0.1
  lambda_s: 1.0
  lambda_l: 1.0
  lambda_e: 1.0

preprocess:
  f0_min: 60.0
  f0_max: 600.0
  wavlm_model: "microsoft/wavlm-large"
  wavlm_layer_idx: 12
  kmeans_n_clusters: 1024
  kmeans_sample_frames: 4800000 # 6s * 16000Hz * 16000 (utts) / 320 (hop_length)
  kmeans_max_per_utt: 200

data:
  # 是否使用缓存的 F0/Token (设为 false 时自动触发动态计算)
  use_cache: true
  f0_dir: "data/processed/f0_abs"
  # f0_dir: "data/processed/f0_log"
  chroma_dir : "data/processed/chroma"
  token_dir: "data/processed/tokens"

anonymization:
  vctk_pool_path: "data/vctk_speaker_vectors.pt"
  num_candidates: 20
  alpha_cond3: 0.9
  alpha_cond4: 0.8
  anon_dim: 256

paths:
  # raw data
  train_dirs: [
    "data/raw/LibriSpeech/train-clean-100",
    "data/raw/LibriSpeech/train-clean-360",
    "data/raw/LibriTTS/train-clean-100",
    "data/raw/LibriTTS/train-clean-360",
  ]
  val_dirs:   ["data/raw/LibriSpeech/dev-clean", "data/raw/LibriTTS/dev-clean"]
  test_dirs:  ["data/raw/LibriSpeech/test-clean", "data/raw/LibriTTS/test-clean"]

  # processed data
  manifest_dir: "data/processed/manifests"
  kmeans_path:  "data/processed/kmeans/kmeans_model.pkl"
  spk_map_path: "data/processed/spk_map.json"

  # outputs
  log_dir:        "runs/"
  test_out_dir:   "data/anonymized_test/"