# configs.yaml
random_seed: 42

model:
  sample_rate: 16000
  n_mels: 80
  dimension: 512
  hop_length: 320
  win_length: 1280
  n_fft: 1280
  speech:
    strides: [8, 5, 4, 2]
    lstm_layers: 2
  speaker:
    style_hidden: 128
    style_head: 2
    style_tcn_kernel: 5
    dropout: 0.1
  bottleneck:
    codebook_size: 1024
    n_q: 8
    decay: 0.99
    commitment_weight: 1.0
    kmeans_init: true
    kmeans_iters: 50
    threshold_ema_dead_code: 2

training:
  batch_size: 48
  max_steps: 500000
  max_epochs: 10
  lr_g: 3.0e-4
  lr_d: 3.0e-4
  gamma: 0.9
  betas: [0.8, 0.99]
  weight_decay: 1.0e-5
  train_num_workers: 20
  val_num_workers: 20
  precision: "bf16-mixed"
  target_samples: 64000
  val_check_interval: 0.2
  early_stop_patience: 10
  early_stop_monitor: "val/rec"
  early_stop_mode: "min"
  log_every_n_steps: 100

losses:
  lambda_r: 45.0
  lambda_a: 1.0
  lambda_c: 0.1
  lambda_s: 1.0
  lambda_l: 1.0
  lambda_e_f0: 1.0
  lambda_e_chroma: 1.0
  lambda_mrstft: 1.0
  lambda_time_l1: 1.0
  f0_type: "log" # "log" or "abs"
  enable_chroma: true
  enable_mrstft: false
  enable_time_l1: false
  mrstft_resolutions:
    - [2048, 320, 1280]
    - [1024, 160, 640]
    - [512, 80, 320]

discriminator:
  enable_mpd: true
  enable_msd: true
  enable_mstft: false

preprocess:
  f0_min: 60.0
  f0_max: 600.0
  wavlm_model: "microsoft/wavlm-large"
  wavlm_layer_idx: 6
  kmeans_n_clusters: 1024
  kmeans_sample_frames: 5000000 # for 320 hop length
  # kmeans_sample_frames: 6250000 # for 256 hop length
  kmeans_max_per_utt: 200

data:
  use_cache: true
  min_duration_sec: 2.0
  f0_dir: "data/processed/f0_log"
  chroma_dir: "data/processed/chroma"
  token_dir: "data/processed/tokens-6"
  f0_abs_dir: "data/processed/f0_abs"
  f0_log_dir: "data/processed/f0_log"

anonymization:
  vctk_pool_path: "data/vctk_speaker_vectors.pt"
  num_candidates: 20
  alpha_cond3: 0.9
  alpha_cond4: 0.8

# 全局默认 STFT 参数（供其他模块回退使用）
stft:
  hop_length: 320
  win_length: 1280
  n_fft: 1280

paths:
  train_dirs: [
    "data/raw/LibriSpeech/train-clean-100",
    "data/raw/LibriSpeech/train-clean-360",
    "data/raw/LibriTTS/train-clean-100",
    "data/raw/LibriTTS/train-clean-360",
  ]
  val_dirs:   ["data/raw/LibriSpeech/dev-clean", "data/raw/LibriTTS/dev-clean"]
  test_dirs:  ["data/raw/LibriSpeech/test-clean", "data/raw/LibriTTS/test-clean"]
  manifest_dir: "data/processed/manifests"
  kmeans_path:  "data/processed/kmeans/kmeans_model-6.pkl"
  log_dir:        "runs/"
  test_out_dir:   "data/anonymized_test/"
